
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      已經開始建置於 2023/7/13 下午 01:16:50。
      
      節點 1 (預設目標) 上的專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj"。
      PrepareForBuild:
        正在建立目錄 "Debug\\"。
        正在建立目錄 "Debug\\CompilerIdC.tlog\\"。
      InitializeBuildStatus:
        由於指定了 "AlwaysCreate"，因此正在建立 "Debug\\CompilerIdC.tlog\\unsuccessfulbuild"。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在刪除檔案 "Debug\\CompilerIdC.tlog\\unsuccessfulbuild"。
        正在變更時間戳記 "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate"。
      專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" (預設目標) 建置完成。
      
      建置成功。
          0 個警告
          0 個錯誤
      
      經過時間 00:00:01.04
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/roger/Desktop/nextteam/CMakeFiles/3.26.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      已經開始建置於 2023/7/13 下午 01:16:52。
      
      節點 1 (預設目標) 上的專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj"。
      PrepareForBuild:
        正在建立目錄 "Debug\\"。
        正在建立目錄 "Debug\\CompilerIdCXX.tlog\\"。
      InitializeBuildStatus:
        由於指定了 "AlwaysCreate"，因此正在建立 "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild"。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在刪除檔案 "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild"。
        正在變更時間戳記 "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate"。
      專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (預設目標) 建置完成。
      
      建置成功。
          0 個警告
          0 個錯誤
      
      經過時間 00:00:00.57
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/roger/Desktop/nextteam/CMakeFiles/3.26.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-mma0sc"
      binary: "C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-mma0sc"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-mma0sc
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_044b2.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        已經開始建置於 2023/7/13 下午 01:16:53。
        
        節點 1 (預設目標) 上的專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-mma0sc\\cmTC_044b2.vcxproj"。
        PrepareForBuild:
          正在建立目錄 "cmTC_044b2.dir\\Debug\\"。
          正在建立目錄 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-mma0sc\\Debug\\"。
          正在建立目錄 "cmTC_044b2.dir\\Debug\\cmTC_044b2.tlog\\"。
        InitializeBuildStatus:
          由於指定了 "AlwaysCreate"，因此正在建立 "cmTC_044b2.dir\\Debug\\cmTC_044b2.tlog\\unsuccessfulbuild"。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_044b2.dir\\Debug\\\\" /Fd"cmTC_044b2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\roger\\Desktop\\cmake-3.26.4-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  著作權所有，並保留一切權利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_044b2.dir\\Debug\\\\" /Fd"cmTC_044b2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\roger\\Desktop\\cmake-3.26.4-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-mma0sc\\Debug\\cmTC_044b2.exe" /INCREMENTAL /ILK:"cmTC_044b2.dir\\Debug\\cmTC_044b2.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-mma0sc/Debug/cmTC_044b2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-mma0sc/Debug/cmTC_044b2.lib" /MACHINE:X64  /machine:x64 cmTC_044b2.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_044b2.vcxproj -> C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-mma0sc\\Debug\\cmTC_044b2.exe
        FinalizeBuildStatus:
          正在刪除檔案 "cmTC_044b2.dir\\Debug\\cmTC_044b2.tlog\\unsuccessfulbuild"。
          正在變更時間戳記 "cmTC_044b2.dir\\Debug\\cmTC_044b2.tlog\\cmTC_044b2.lastbuildstate"。
        專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-mma0sc\\cmTC_044b2.vcxproj" (預設目標) 建置完成。
        
        建置成功。
            0 個警告
            0 個錯誤
        
        經過時間 00:00:00.58
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/roger/Desktop/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-ealwsk"
      binary: "C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-ealwsk"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-ealwsk
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_eb5a5.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        已經開始建置於 2023/7/13 下午 01:16:54。
        
        節點 1 (預設目標) 上的專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-ealwsk\\cmTC_eb5a5.vcxproj"。
        PrepareForBuild:
          正在建立目錄 "cmTC_eb5a5.dir\\Debug\\"。
          正在建立目錄 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-ealwsk\\Debug\\"。
          正在建立目錄 "cmTC_eb5a5.dir\\Debug\\cmTC_eb5a5.tlog\\"。
        InitializeBuildStatus:
          由於指定了 "AlwaysCreate"，因此正在建立 "cmTC_eb5a5.dir\\Debug\\cmTC_eb5a5.tlog\\unsuccessfulbuild"。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_eb5a5.dir\\Debug\\\\" /Fd"cmTC_eb5a5.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Users\\roger\\Desktop\\cmake-3.26.4-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  著作權所有，並保留一切權利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_eb5a5.dir\\Debug\\\\" /Fd"cmTC_eb5a5.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Users\\roger\\Desktop\\cmake-3.26.4-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-ealwsk\\Debug\\cmTC_eb5a5.exe" /INCREMENTAL /ILK:"cmTC_eb5a5.dir\\Debug\\cmTC_eb5a5.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-ealwsk/Debug/cmTC_eb5a5.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/roger/Desktop/nextteam/CMakeFiles/CMakeScratch/TryCompile-ealwsk/Debug/cmTC_eb5a5.lib" /MACHINE:X64  /machine:x64 cmTC_eb5a5.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_eb5a5.vcxproj -> C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-ealwsk\\Debug\\cmTC_eb5a5.exe
        FinalizeBuildStatus:
          正在刪除檔案 "cmTC_eb5a5.dir\\Debug\\cmTC_eb5a5.tlog\\unsuccessfulbuild"。
          正在變更時間戳記 "cmTC_eb5a5.dir\\Debug\\cmTC_eb5a5.tlog\\cmTC_eb5a5.lastbuildstate"。
        專案 "C:\\Users\\roger\\Desktop\\nextteam\\CMakeFiles\\CMakeScratch\\TryCompile-ealwsk\\cmTC_eb5a5.vcxproj" (預設目標) 建置完成。
        
        建置成功。
            0 個警告
            0 個錯誤
        
        經過時間 00:00:00.65
        
      exitCode: 0
...
